"""
Live probe of a Dataloy tenant's public info endpoint
(https://<subdomain>.dataloy.com/ws/rest/dataloy/info) — no auth required,
confirmed against three real tenants. On-demand only: this hits customer-
owned infrastructure directly, not an API we control, so it's triggered by
a support engineer clicking "Sync", never on a schedule.

Not every tenant lives under *.dataloy.com — some run on the customer's own
domain entirely (e.g. https://vms.klaveness.com/ws/rest/dataloy/info), so
the input is accepted two ways: a bare tenant code ("sfl") gets wrapped into
the standard dataloy.com URL, but anything that already looks like a full
URL (starts with http:// or https://) is used exactly as given — never
force-rewritten onto *.dataloy.com.

Confirmed live response shape:
  {"release": "8.25.3-R", "jvmsMode": false, "isPureWeb": true,
   "isAuth0Installation": true, "isAgencyNomination": false,
   "isAzureInstallation": false, "sizeOfSerializedCache": 0,
   "threadKeys": "[]", "amplitudeApiKey": null, "threadMapSize": -8,
   "threadMapKeys": "[]", "environment": "prod"}

Only a subset of fields is stable/meaningful per-tenant config; the rest
(sizeOfSerializedCache, threadKeys, threadMapSize, threadMapKeys,
amplitudeApiKey, isAgencyNomination) is live runtime/debug state and is
deliberately not persisted.
"""
import logging
import re

import httpx
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.services.jira import _COMPANY_SUFFIXES

logger = logging.getLogger(__name__)

_VERSION_NUM = re.compile(r"\d+")


def _version_tuple(v: str | None) -> tuple[int, ...] | None:
    """Real element-wise version comparison — same fix as releases.py's own
    _version_tuple (a naive parseFloat("8.30") < parseFloat("8.9") is a real
    bug for two-digit minors). Kept as its own small copy here rather than
    importing a router's private helper into a service module."""
    if not v:
        return None
    parts = _VERSION_NUM.findall(v)
    return tuple(int(p) for p in parts) if parts else None


async def latest_completed_upgrade_version(db: AsyncSession, customer_id: int, environment: str) -> str | None:
    """The most recent real, parseable to_version from a Verified Done
    Upgrade for this customer+environment — the fallback source of truth
    when the live tenant probe can't be reached (confirmed real gap:
    Spliethoff's PROD tenant sync has been timing out since 2026-09-08,
    leaving CustomerTenantInfo.release/Customer.prod_version stuck on a
    Feb-2026 value while a real completed PROD upgrade to 8.31.3 already
    exists locally). "Unknown" and blank to_version values are skipped —
    they're not a real fact to fall back to."""
    from app.models.upgrade import Upgrade

    result = await db.execute(
        select(Upgrade).where(
            Upgrade.customer_id == customer_id,
            Upgrade.environment == environment,
            Upgrade.stage == "Verified Done",
        )
    )
    best: tuple[tuple[int, ...], str, object] | None = None
    for u in result.scalars().all():
        tup = _version_tuple(u.to_version)
        if tup is None:
            continue
        when = u.date_done or u.verified_at
        if best is None or (when is not None and (best[2] is None or when > best[2])):
            best = (tup, u.to_version, when)
    return best[1] if best else None


class TenantInfoResult:
    def __init__(self, data: dict | None = None, error: str | None = None):
        self.data = data
        self.error = error


def _resolve_url(subdomain_or_url: str) -> str:
    value = subdomain_or_url.strip()
    if value.lower().startswith("http://") or value.lower().startswith("https://"):
        return value
    return f"https://{value}.dataloy.com/ws/rest/dataloy/info"


_PAREN_ABBREVIATION = re.compile(r"\(([A-Za-z0-9]{2,8})\)\s*$")


def _squash_company_name(name: str) -> str:
    """Like jira.py's _normalize_company_name() (same legal-suffix strip,
    reused rather than duplicated) but also removes whitespace entirely —
    matches the real observed subdomain pattern ("Golden Ocean" ->
    "goldenocean", "Cemvision AB" -> "cemvision"), whereas the Jira-matching
    normalizer deliberately keeps single spaces.

    Confirmed live this is NOT a universal derivation — real subdomains are
    manually chosen per customer, not generated by any one rule (e.g. real
    subdomain for "Agriculture & Energy Carriers (AEC)" is "aecarriers",
    matching neither a full squash nor the parenthetical abbreviation). This
    is a best-effort candidate source among several, not a guarantee — the
    discovery flow tries multiple candidates and still requires a human
    Accept, exactly because no single rule reconstructs real branding
    choices reliably."""
    value = name.lower()
    value = _COMPANY_SUFFIXES.sub(" ", value)
    value = "".join(ch for ch in value if ch.isalnum())
    return value


# Real suffix patterns, derived directly from the 117 CustomerTenantInfo rows
# already on file — not a generic guess. PROD is usually bare, sometimes
# "-prod"; TEST varies more ("-test" most common, "-web-test" and "-test2"
# both real). DEV is deliberately out of scope (see tenant discovery plan).
_CANDIDATE_SUFFIXES: dict[str, list[str]] = {
    "PROD": ["", "-prod"],
    "TEST": ["-test", "-web-test", "-test2"],
}


def generate_tenant_candidates(name: str) -> dict[str, list[str]]:
    bases = [_squash_company_name(name)]
    # Just the first word, suffix-stripped and squashed, is often the real
    # brand fragment used — confirmed live: "Stena Rederi AB" -> real
    # subdomain "stena" (not "stenarederi" — "Rederi" is a real Norwegian/
    # Swedish word for "shipping company", not a legal suffix, so the full
    # squash misses it), "Harren Bulk Shipping" -> real subdomain "harren".
    stripped = _COMPANY_SUFFIXES.sub(" ", name.lower()).strip()
    first_word = re.sub(r"[^a-z0-9]", "", stripped.split(" ")[0]) if stripped else ""
    if first_word and first_word not in bases:
        bases.append(first_word)
    # A trailing parenthetical like "(KGJS)" is sometimes the real subdomain
    # itself (confirmed: Kristian Gerhard Jebsen Skipsrederi AS (KGJS) ->
    # real subdomain "kgjs") — tried as an additional, earlier candidate,
    # not a replacement, since it doesn't hold universally (AEC's real
    # subdomain is "aecarriers", not "aec"). Acronym-of-initials names
    # (Universal Africa Lines BV -> real subdomain "ual") are a real pattern
    # too but are NOT covered here — chasing every naming convention has
    # diminishing returns; the discovery flow's honest "no candidate found"
    # outcome for these is expected, not a bug, per the tenant-discovery plan.
    paren_match = _PAREN_ABBREVIATION.search(name)
    if paren_match:
        bases.insert(0, paren_match.group(1).lower())

    out: dict[str, list[str]] = {}
    for env, suffixes in _CANDIDATE_SUFFIXES.items():
        candidates = []
        for base in bases:
            for suffix in suffixes:
                candidate = f"{base}{suffix}"
                if candidate not in candidates:
                    candidates.append(candidate)
        out[env] = candidates
    return out


async def fetch_tenant_info(subdomain_or_url: str) -> TenantInfoResult:
    url = _resolve_url(subdomain_or_url)
    try:
        async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
            resp = await client.get(url)
            resp.raise_for_status()
            return TenantInfoResult(data=resp.json())
    except httpx.TimeoutException:
        return TenantInfoResult(error="Timed out — tenant may be VPN/firewall-restricted")
    except httpx.HTTPStatusError as exc:
        return TenantInfoResult(error=f"HTTP {exc.response.status_code}")
    except Exception as exc:
        logger.warning("Tenant info fetch failed for %s: %s", url, exc)
        return TenantInfoResult(error=str(exc)[:400])
