"""phase1_core_models

Revision ID: 143d70e75e2e
Revises: 
Create Date: 2026-08-18 17:18:31.089365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '143d70e75e2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('csm', sa.String(length=100), nullable=False),
    sa.Column('arr_gbp', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('contacts', sa.Text(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('sla_tier', sa.String(length=50), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=30), nullable=False),
    sa.Column('churn_risk', sa.String(length=20), nullable=False),
    sa.Column('upgrades_used', sa.Integer(), nullable=False),
    sa.Column('upgrades_limit', sa.Integer(), nullable=False),
    sa.Column('prod_version', sa.String(length=30), nullable=True),
    sa.Column('test_version', sa.String(length=30), nullable=True),
    sa.Column('infra', sa.String(length=20), nullable=False),
    sa.Column('ip_fw', sa.Boolean(), nullable=False),
    sa.Column('wildfly8', sa.Boolean(), nullable=False),
    sa.Column('sso', sa.String(length=50), nullable=False),
    sa.Column('integrations', sa.String(length=200), nullable=False),
    sa.Column('api_customer', sa.Boolean(), nullable=False),
    sa.Column('pref_days', sa.String(length=100), nullable=True),
    sa.Column('notice_required', sa.String(length=50), nullable=True),
    sa.Column('blackout_periods', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('released_at', sa.Date(), nullable=False),
    sa.Column('defects_fixed', sa.Integer(), nullable=False),
    sa.Column('improvements', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_version'), 'releases', ['version'], unique=True)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('jira_ref', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('case_type', sa.String(length=30), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('sla_days', sa.Integer(), nullable=True),
    sa.Column('sla_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_open', sa.Integer(), nullable=False),
    sa.Column('defect_status', sa.String(length=200), nullable=True),
    sa.Column('root_cause', sa.String(length=200), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('linked_case_ref', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_customer_id'), 'cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cases_jira_ref'), 'cases', ['jira_ref'], unique=False)
    op.create_table('customer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_notes_customer_id'), 'customer_notes', ['customer_id'], unique=False)
    op.create_table('migration_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('assignee', sa.String(length=50), nullable=True),
    sa.Column('complexity', sa.String(length=20), nullable=False),
    sa.Column('ip_fw', sa.Boolean(), nullable=False),
    sa.Column('requires_upgrade', sa.Boolean(), nullable=False),
    sa.Column('stalled', sa.Boolean(), nullable=False),
    sa.Column('stalled_days', sa.Integer(), nullable=False),
    sa.Column('downtime_agreed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_notes', sa.Text(), nullable=True),
    sa.Column('integration_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_projects_customer_id'), 'migration_projects', ['customer_id'], unique=True)
    op.create_table('training_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source_case_ref', sa.String(length=30), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_gaps_customer_id'), 'training_gaps', ['customer_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('topic_area', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('delivered_by', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=200), nullable=True),
    sa.Column('follow_up_needed', sa.Boolean(), nullable=False),
    sa.Column('follow_up_text', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_customer_id'), 'training_sessions', ['customer_id'], unique=False)
    op.create_table('upgrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('jira_ref', sa.String(length=30), nullable=True),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('from_version', sa.String(length=30), nullable=True),
    sa.Column('to_version', sa.String(length=30), nullable=False),
    sa.Column('upgrade_type', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_done', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upgrades_customer_id'), 'upgrades', ['customer_id'], unique=False)
    op.create_index(op.f('ix_upgrades_jira_ref'), 'upgrades', ['jira_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upgrades_jira_ref'), table_name='upgrades')
    op.drop_index(op.f('ix_upgrades_customer_id'), table_name='upgrades')
    op.drop_table('upgrades')
    op.drop_index(op.f('ix_training_sessions_customer_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_training_gaps_customer_id'), table_name='training_gaps')
    op.drop_table('training_gaps')
    op.drop_index(op.f('ix_migration_projects_customer_id'), table_name='migration_projects')
    op.drop_table('migration_projects')
    op.drop_index(op.f('ix_customer_notes_customer_id'), table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_index(op.f('ix_cases_jira_ref'), table_name='cases')
    op.drop_index(op.f('ix_cases_customer_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_releases_version'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
