"""add unmatched upgrade customers and name aliases

Revision ID: 55d69f6fb120
Revises: a61d58fc18ec
Create Date: 2026-08-25 11:41:11.785771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55d69f6fb120'
down_revision: Union[str, None] = 'a61d58fc18ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unmatched_upgrade_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.Column('sample_jira_refs', sa.String(length=500), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unmatched_upgrade_customers_customer_name'), 'unmatched_upgrade_customers', ['customer_name'], unique=True)
    op.create_table('customer_name_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_name_aliases_alias_name'), 'customer_name_aliases', ['alias_name'], unique=True)
    op.create_index(op.f('ix_customer_name_aliases_customer_id'), 'customer_name_aliases', ['customer_id'], unique=False)
    # NOTE: autogenerate also proposed touching sso_onboarding's unique
    # constraint/index (unrelated pre-existing model/DB drift, not part of
    # this change) — deliberately left out, same as the last migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_name_aliases_customer_id'), table_name='customer_name_aliases')
    op.drop_index(op.f('ix_customer_name_aliases_alias_name'), table_name='customer_name_aliases')
    op.drop_table('customer_name_aliases')
    op.drop_index(op.f('ix_unmatched_upgrade_customers_customer_name'), table_name='unmatched_upgrade_customers')
    op.drop_table('unmatched_upgrade_customers')
    # ### end Alembic commands ###
