"""add customer hypercare fields

Revision ID: 6294c7e7e387
Revises: 91a4c2855f79
Create Date: 2026-08-25 15:10:05.310153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6294c7e7e387'
down_revision: Union[str, None] = '91a4c2855f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('hypercare_until', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('hypercare_reason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'hypercare_reason')
    op.drop_column('customers', 'hypercare_until')
    # ### end Alembic commands ###
