"""add cancellations table and customer status

Revision ID: 91a4c2855f79
Revises: 55d69f6fb120
Create Date: 2026-08-25 14:28:17.917733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91a4c2855f79'
down_revision: Union[str, None] = '55d69f6fb120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('jira_ref', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('devops_contact', sa.String(length=150), nullable=True),
    sa.Column('devops_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cancellations_customer_id'), 'cancellations', ['customer_id'], unique=True)
    op.add_column('customers', sa.Column('status', sa.String(length=20), nullable=False, server_default='Active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'status')
    op.drop_index(op.f('ix_cancellations_customer_id'), table_name='cancellations')
    op.drop_table('cancellations')
    # ### end Alembic commands ###
