"""add customer tenant info and login notes

Revision ID: a61d58fc18ec
Revises: e6f7a8b9c0d1
Create Date: 2026-08-25 08:42:57.001923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a61d58fc18ec'
down_revision: Union[str, None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_tenant_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('release', sa.String(length=30), nullable=True),
    sa.Column('reported_environment', sa.String(length=20), nullable=True),
    sa.Column('is_azure_installation', sa.Boolean(), nullable=True),
    sa.Column('is_auth0_installation', sa.Boolean(), nullable=True),
    sa.Column('is_jvms_mode', sa.Boolean(), nullable=True),
    sa.Column('is_pure_web', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'environment', name='uq_customer_tenant_env')
    )
    op.create_index(op.f('ix_customer_tenant_info_customer_id'), 'customer_tenant_info', ['customer_id'], unique=False)
    op.add_column('customers', sa.Column('tenant_login_notes', sa.Text(), nullable=True))
    # NOTE: autogenerate also proposed touching sso_onboarding's unique
    # constraint/index (unrelated pre-existing model/DB drift, not part of
    # this change) — deliberately left out to keep this migration scoped to
    # only what it says it does.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'tenant_login_notes')
    op.drop_index(op.f('ix_customer_tenant_info_customer_id'), table_name='customer_tenant_info')
    op.drop_table('customer_tenant_info')
    # ### end Alembic commands ###
